# Generated by Django 2.2 on 2020-04-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allnews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'All News'},
        ),
        migrations.AlterModelOptions(
            name='gadgetnews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'Gadget News'},
        ),
        migrations.AlterModelOptions(
            name='globalnews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'Global Tech News'},
        ),
        migrations.AlterModelOptions(
            name='technews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'Tech News'},
        ),
        migrations.AlterModelOptions(
            name='telconews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'Telecom News'},
        ),
        migrations.AlterField(
            model_name='allnews',
            name='posted',
            field=models.CharField(default='April 08, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='gadgetnews',
            name='posted',
            field=models.CharField(default='April 08, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalnews',
            name='posted',
            field=models.CharField(default='April 08, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='technews',
            name='posted',
            field=models.CharField(default='April 08, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='telconews',
            name='posted',
            field=models.CharField(default='April 08, 2020', max_length=20),
        ),
    ]
