# Generated by Django 2.2 on 2020-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrappednews',
            options={'ordering': ['-scrapped'], 'verbose_name_plural': 'Scrapped News'},
        ),
        migrations.AlterField(
            model_name='scrappednews',
            name='category',
            field=models.CharField(default='Tech News', max_length=5),
        ),
    ]
