# Generated by Django 2.2 on 2020-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_auto_20200603_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappednews',
            name='category',
            field=models.CharField(default='Tech News', max_length=20),
        ),
    ]
