# Generated by Django 2.2 on 2020-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_auto_20200408_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='posted',
            field=models.CharField(default='April 09, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='gadgetnews',
            name='posted',
            field=models.CharField(default='April 09, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalnews',
            name='posted',
            field=models.CharField(default='April 09, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='technews',
            name='posted',
            field=models.CharField(default='April 09, 2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='telconews',
            name='posted',
            field=models.CharField(default='April 09, 2020', max_length=20),
        ),
    ]
