# Generated by Django 2.2 on 2020-06-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20200603_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.EmailField(max_length=254, unique=True)),
                ('subscribed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribers List',
                'ordering': ['-subscribed'],
            },
        ),
        migrations.AlterField(
            model_name='scrappednews',
            name='posted',
            field=models.CharField(default='June 04, 2020', max_length=20),
        ),
    ]
