# Generated by Django 2.2 on 2020-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_auto_20200604_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('messaged_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Message from Customers',
            },
        ),
    ]
